services:
  Tardigrades\Command\CreateApplicationCommand:
    arguments:
      $applicationManager: '@Tardigrades\SectionField\Service\DoctrineApplicationManager'

  Tardigrades\Command\UpdateApplicationCommand:
    arguments:
      $applicationManager: '@Tardigrades\SectionField\Service\DoctrineApplicationManager'

  Tardigrades\Command\DeleteApplicationCommand:
    arguments:
      $applicationManager: '@Tardigrades\SectionField\Service\DoctrineApplicationManager'

  Tardigrades\Command\ListApplicationCommand:
    arguments:
      $applicationManager: '@Tardigrades\SectionField\Service\DoctrineApplicationManager'

  Tardigrades\Command\CreateLanguageCommand:
    arguments:
      $languageManager: '@Tardigrades\SectionField\Service\DoctrineLanguageManager'

  Tardigrades\Command\UpdateLanguageCommand:
    arguments:
      $languageManager: '@Tardigrades\SectionField\Service\DoctrineLanguageManager'

  Tardigrades\Command\DeleteLanguageCommand:
    arguments:
      $languageManager: '@Tardigrades\SectionField\Service\DoctrineLanguageManager'

  Tardigrades\Command\ListLanguageCommand:
    arguments:
      $languageManager: '@Tardigrades\SectionField\Service\DoctrineLanguageManager'

  Tardigrades\Command\InstallFieldTypeCommand:
    arguments:
      $fieldTypeManager: '@Tardigrades\SectionField\Service\DoctrineFieldTypeManager'

  Tardigrades\Command\UpdateFieldTypeCommand:
    arguments:
      $fieldTypeManager: '@Tardigrades\SectionField\Service\DoctrineFieldTypeManager'

  Tardigrades\Command\DeleteFieldTypeCommand:
    arguments:
      $fieldTypeManager: '@Tardigrades\SectionField\Service\DoctrineFieldTypeManager'

  Tardigrades\Command\ListFieldTypeCommand:
    arguments:
      $fieldTypeManager: '@Tardigrades\SectionField\Service\DoctrineFieldTypeManager'

  Tardigrades\Command\CreateSectionCommand:
    arguments:
      $sectionManager: '@Tardigrades\SectionField\Service\DoctrineSectionManager'

  Tardigrades\Command\UpdateSectionCommand:
    arguments:
      $sectionManager: '@Tardigrades\SectionField\Service\DoctrineSectionManager'

  Tardigrades\Command\UpdateSectionsCommand:
    arguments:
      $sectionManager: '@Tardigrades\SectionField\Service\DoctrineSectionManager'

  Tardigrades\Command\RestoreSectionCommand:
    arguments:
      $sectionManager: '@Tardigrades\SectionField\Service\DoctrineSectionManager'
      $sectionHistoryManager: '@Tardigrades\SectionField\Service\DoctrineSectionHistoryManager'

  Tardigrades\Command\DeleteSectionCommand:
    arguments:
      $sectionManager: '@Tardigrades\SectionField\Service\DoctrineSectionManager'

  Tardigrades\Command\ListSectionCommand:
    arguments:
      $sectionManager: '@Tardigrades\SectionField\Service\DoctrineSectionManager'

  Tardigrades\Command\GenerateSectionCommand:
    arguments:
      $sectionManager: '@Tardigrades\SectionField\Service\DoctrineSectionManager'
      $entityGenerator: '@section_field.generator'

  Tardigrades\Command\CreateFieldCommand:
    arguments:
      $fieldManager: '@Tardigrades\SectionField\Service\DoctrineFieldManager'

  Tardigrades\Command\UpdateFieldCommand:
    arguments:
      $fieldManager: '@Tardigrades\SectionField\Service\DoctrineFieldManager'

  Tardigrades\Command\DeleteFieldCommand:
    arguments:
      $fieldManager: '@Tardigrades\SectionField\Service\DoctrineFieldManager'

  Tardigrades\Command\ListFieldCommand:
    arguments:
      $fieldManager: '@Tardigrades\SectionField\Service\DoctrineFieldManager'

  Tardigrades\Command\InstallDirectoryCommand:
    arguments:
      $applicationManager: '@Tardigrades\SectionField\Service\DoctrineApplicationManager'
      $languageManager: '@Tardigrades\SectionField\Service\DoctrineLanguageManager'
      $sectionManager: '@Tardigrades\SectionField\Service\DoctrineSectionManager'
      $fieldManager: '@Tardigrades\SectionField\Service\DoctrineFieldManager'
      $fieldTypeManager: '@Tardigrades\SectionField\Service\DoctrineFieldTypeManager'
